### ISSUE TITLE
Expose functionality via REST API

### ISSUE THREAD

**Issue by jusso-dev** [neeru1207/AI_Sudoku#13]
Awesome project, I'm just wondering, is there appetite to wrap the core functionality into a Flask rest endpoint? or at least point me to the core functionality required to expose said core functionality into a rest endpoint?

**Comment by neeru1207** [comment]
I am not familiar with Web development so I don't quite understand what you are saying

**Comment by rajvijay68** [comment]
What @jusso-dev  is saying is - wouldn't it be awesome if this project was hosted as a webapp, and people could play with it by uploading images!
Many people display their projects by deploying a live demo. Deploying this as a flask/django app on heroku,AWS would be awesome!
