### ISSUE TITLE
How do I run this code in Mac?

### ISSUE THREAD

**Issue by shoaib1992** [neeru1207/AI_Sudoku#14]
I am new to GitHub and don't really know how to run this code in MacBook.I tried downloading zip file and running the .py extension files in Pycharm but getting many errors.Can you please guide me?

**Comment by neeru1207** [comment]
You need to install Python, Pip and all the required packages on mac before running this application. kindly refer online as to how to download and install python. Then proceed to install all the required packages.

**Comment by HassanBinHaroon** [comment]
Take a look at the following repository too. 

https://github.com/HassanBinHaroon/deep-hough-transform
