### ISSUE TITLE
No module named 'tkinter'

### ISSUE THREAD

**Issue by bdeshayes** [neeru1207/AI_Sudoku#17]
(sudokuenv) C:\Users\Bruno\sudokuenv\AI_Sudoku-master>python Run.py
Traceback (most recent call last):
  File "Run.py", line 2, in <module>
    from MainUI import MainUI
  File "C:\Users\Bruno\sudokuenv\AI_Sudoku-master\MainUI.py", line 4, in <module>
    from tkinter import *
ModuleNotFoundError: No module named 'tkinter'

**Comment by neeru1207** [comment]
Kindly rectify the issue and open a pull request

**Comment by neeru1207** [comment]
If you are using Python2 it is Tkinter not tkinter
