### ISSUE TITLE
Doesn't reveal solution

### ISSUE THREAD

**Issue by rajvijay68** [neeru1207/AI_Sudoku#3]
Amazing work!

But it doesn't solve the sudoku.
It says invalid board for every image.

**Comment by neeru1207** [comment]
Thanks a lot for raising the issue. I have rectified the issue and committed the changes. Kindly check again.

**Comment by rajvijay68** [comment]
@neeru1207  It still doesn't work

Tried this image : 
![sudoku2](https://user-images.githubusercontent.com/26388709/71542106-67ae7900-2988-11ea-9c4e-00182a3f43f1.jpg)


Got this  : 

![sudoku-ai-not-working](https://user-images.githubusercontent.com/26388709/71542092-261dce00-2988-11ea-8134-4e5b6113601a.png)


Maybe the KNN isn't good enough with k=3?

**Comment by davixcky** [comment]
I found the error. Look the squares 3 and 6, both have the 8 in the same column

**Comment by davixcky** [comment]
The error is because, the 9 of the square 6 (2,1) , was changed by 8

**Comment by neeru1207** [comment]
The detection and recognition isn't 100% accurate obviously. So I had provided an option for the user to rectify the entries. So manually rectify the entries and click on reveal solutions
