### ISSUE TITLE
Reveal Solution is wrong

### ISSUE THREAD

**Issue by URvesh109** [neeru1207/AI_Sudoku#8]
Awesome example fo AI, but solution is wrong. Mine also get wrong at first then I rectified my mistake. Implemented in ReactNative

<img width="583" alt="Screenshot 2019-12-31 at 10 36 51" src="https://user-images.githubusercontent.com/26654227/71610770-cc044f00-2bb9-11ea-9693-cf11b3499e97.png">

Check this link

https://www.linkedin.com/posts/urvesh-ghoderao-196817160_algorithm-reactnative-activity-6570996500195840000-EtyQ

**Comment by neeru1207** [comment]
Pull changes and try again. This issue has long been rectified
